# Site settings
title: The Flybase Blog
email: roger@flybase.io
description: > # this means to ignore newlines until "baseurl:"
  Flybase is a real-time backend as a service that allows you to create incredible apps. Save, Store and Update Data in real-time directly from the browser or mobile client using only javascript, REST API, or native iOS or Android code. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.flybase.io" # the base hostname & protocol for your site
twitter_username: flybaseio
github_username:  flybaseio

twitter:
  username: "@flybaseio"

facebook:
  app_id: "474703915878478"
  publisher: "1416546778590314"
  admins: "604781976"


social:
  name: Roger Stringer
  links:
    - https://twitter.com/flybaseio
    - https://www.facebook.com/flybaseio
    - https://github.com/flybaseio

# Build settings
permalink: pretty
markdown: kramdown
redcarpet:
  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]
highlighter: rouge
paginate: 10

github:
  repo: flybaseio/flybaseio.github.io
  branch: master

gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
